### ISSUE TITLE
1.0.0.1 crashes dedicated server Forge 1.14.4 build 28.1.80

### ISSUE THREAD

**Issue by kreezxil** [DashEightMate/ThunderAndLightning#1]
Notes:
     nosuchmethoderror

crash report:
http://paste.ubuntu.com/p/HrCkxkzC5q/

fml server latest:
http://paste.ubuntu.com/p/TqYvYbY8Zt/

**Comment by kreezxil** [comment]
also 1.0.0.0 has the same issue

Issue:  1.0.0.0 crashes dedicated server Forge 1.14.4 build 28.1.80

Notes:
     no such method error

crash report:
http://paste.ubuntu.com/p/wpq5THYS72/

fml server latest:
http://paste.ubuntu.com/p/zwxTzskX8D/


# most likely cause
client side classes in the side that runs on the server.

**Comment by marshoepial** [comment]
Sorry for the delay, I took a bit of a break from mods. I'll take a look, it's definitely a server/client issue. I'll get back to you. Thanks for the report.

**Comment by marshoepial** [comment]
Just fixed, thanks for letting me know. I've made the methods work on both sides.
[https://github.com/DashEightMate/ThunderAndLightning/commit/004eca25d5cbf40656571ea55ee7e49564a7f228](commit)
The fixed jar is on the curseforge under version 1.0.0.2
